### ISSUE TITLE
Arbor fails to compile with Intel compiler

### ISSUE THREAD

**Issue by heplesser** [arbor-sim/nsuite#86]
Current Arbor master compiles fine with GCC 8.3.0, but using ICC 19.0.3.199, I get the following error:
```
[ 52%] Building CXX object arbor/CMakeFiles/arbor.dir/tree.cpp.o
/p/home/jusers/plesser1/deep/work/Work/Arbor/nsuite-dam-gpu/build/arbor/arbor/mechcat.cpp(458): error: call of an object of a class type without appropriate operator() or conversion functions to pointer-to-function type
                  self(self, p->parent, over);
                  ^
          detected during instantiation of function "lambda [](auto &, const std::__cxx11::string &, arb::mechanism_overrides &)->void [with <auto-1>=lambda [](auto &, const std::__cxx11::string &, arb::mechanism_overrides &)->void]" at line 473
```
I am building via the nsuite/install_local.sh script.

Unfortunately, on the system I am working on netCDF is only available with the Intel compiler and ParastationMPI, so I rather need to use the Intel compiler.

**Comment by bcumming** [comment]
Arbor can't be built with the Intel compiler, which is meant to simplify things for users, though ironically not in this case.

If you are linking against netCDF compiled with Intel, you should still be able to use GNU, so long as netCDF wasn't compiled with a pre-gcc 5 version of the GNU C++ standard library.

ParastationMPI has GNU versions too. Are they not available on this system?

**Comment by bcumming** [comment]
Here are our docs on compilers.

https://arbor.readthedocs.io/en/latest/install.html#compilers

**Comment by heplesser** [comment]
@heplesser Sorry, I should have read the documentation first!

**Comment by bcumming** [comment]
Sorry HEP, I was working on some suggestions for how to compile without the Intel compiler. If you are still interested...

NetCDF is not required to run the benchmarks, and we can build the benchmarks for single socket/node without MPI.

So can we try to build with GCC with MPI disabled by setting `ns_with_mpi=OFF` in your configuration script?

**Comment by heplesser** [comment]
@bcumming That seems to work. I though "validation first, benchmarking second" (no point to benchmark code generating invalid results, after all), so I hadn't even tried to run the benchmarks once building the validation failed.

But the benchmark seems to run, until it tries to execute `bc`, which is missing from the system (it is a rather special system). I will check with the admins there to get it installed. 

Feel free to close the issue again.

**Comment by bcumming** [comment]
Good to hear that you got it to compile.

We should add a simple validation check to each benchmark, that tests whether a sane spike sequence was generated, so that only running benchmarks would still have a minimal sanity check.
